import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/ui/footer";
import { Header } from "@/components/ui/header";
import { HeroGeometric } from "@/components/ui/shape-landing-hero";
import Providers from "@/components/providers";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Header />
                <main className="min-h-screen pb-24 relative">
                    <HeroGeometric />
                    <Providers>{children}</Providers>
                </main>
                <Footer />
            </body>
        </html>
    );
}
